name: Deploy Static Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEV_AWS_REGION: eu-west-2
  PROD_AWS_REGION: us-east-1

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (Dev)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.DEV_AWS_REGION }}

      - name: Deploy Static Files to Dev
        working-directory: ./application
        run: |
          aws s3 sync . "s3://${{ secrets.DEV_BUCKET_NAME }}" \
            --exclude "*.git/*" \
            --exclude "deploy.sh" \
            --exclude "README.md" \
            --region "${{ env.DEV_AWS_REGION }}"

  # deploy-prod:
  #   name: Deploy to Prod
  #   runs-on: ubuntu-latest
  #   environment: prod
  #   needs: deploy-dev

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Configure AWS Credentials (Prod)
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ env.PROD_AWS_REGION }}

  #     - name: Wait 5 minutes before prod deployment
  #       run: sleep 300

  #     - name: Deploy Static Files to Prod
  #       working-directory: ./application
  #       run: |
  #         aws s3 sync . "s3://${{ secrets.PROD_BUCKET_NAME }}" \
  #           --exclude "*.git/*" \
  #           --exclude "deploy.sh" \
  #           --exclude "README.md" \
  #           --region "${{ env.PROD_AWS_REGION }}" 
